border_width = 6
margin = [4, 4]
default_border_color = "#6d4b4a"
floating_border_color = "#FB8B86"
focused_border_color = "#e1cbc6"


col1 = "#9E9DA4"
col2 = "#A49DA4"
col3 = "#A5A4AA"
col4 = "#B2A0A0"
col5 = "#C79091"
col6 = "#FB8B86"
col7 = "#e1cbc6"
col8 = "#9d8e8a"
col9 = "#9E9DA4"
col10 = "#A49DA4"
col11 = "#A5A4AA"
col12 = "#B2A0A0"
col13 = "#C79091"
col14 = "#FB8B86"
col15 = "#e1cbc6"



background = "#6d4b4a"
foreground = "#e1cbc6"
