border_width = 6
margin = [4, 4]
default_border_color = "#01000C"
floating_border_color = "#E4648F"
focused_border_color = "#90e0d2"


col1 = "#AB345E"
col2 = "#F25D70"
col3 = "#3EB673"
col4 = "#ECB370"
col5 = "#205792"
col6 = "#E4648F"
col7 = "#90e0d2"
col8 = "#649c93"
col9 = "#AB345E"
col10 = "#F25D70"
col11 = "#3EB673"
col12 = "#ECB370"
col13 = "#205792"
col14 = "#E4648F"
col15 = "#90e0d2"



background = "#01000C"
foreground = "#90e0d2"
