border_width = 6
margin = [4, 4]
default_border_color = "#0d0a1e"
floating_border_color = "#D32C98"
focused_border_color = "#e699cd"


col1 = "#E73372"
col2 = "#54228F"
col3 = "#5D2391"
col4 = "#2A55B2"
col5 = "#A02FA7"
col6 = "#D32C98"
col7 = "#e699cd"
col8 = "#a16b8f"
col9 = "#E73372"
col10 = "#54228F"
col11 = "#5D2391"
col12 = "#2A55B2"
col13 = "#A02FA7"
col14 = "#D32C98"
col15 = "#e699cd"



background = "#0d0a1e"
foreground = "#e699cd"
