border_width = 6
margin = [4, 4]
default_border_color = "#010816"
floating_border_color = "#02E0E7"
focused_border_color = "#a0dfdf"


col1 = "#006E8D"
col2 = "#006F97"
col3 = "#0062B5"
col4 = "#0193AA"
col5 = "#01B3C9"
col6 = "#02E0E7"
col7 = "#a0dfdf"
col8 = "#709c9c"
col9 = "#006E8D"
col10 = "#006F97"
col11 = "#0062B5"
col12 = "#0193AA"
col13 = "#01B3C9"
col14 = "#02E0E7"
col15 = "#a0dfdf"



background = "#010816"
foreground = "#a0dfdf"
