border_width = 6
margin = [4, 4]
default_border_color = "#010119"
floating_border_color = "#4ABBC3"
focused_border_color = "#a4c8e2"


col1 = "#2F2D8A"
col2 = "#305898"
col3 = "#4D4AA8"
col4 = "#505DA2"
col5 = "#B27185"
col6 = "#4ABBC3"
col7 = "#a4c8e2"
col8 = "#728c9e"
col9 = "#2F2D8A"
col10 = "#305898"
col11 = "#4D4AA8"
col12 = "#505DA2"
col13 = "#B27185"
col14 = "#4ABBC3"
col15 = "#a4c8e2"



background = "#010119"
foreground = "#a4c8e2"
