border_width = 6
margin = [4, 4]
default_border_color = "#0E0908"
floating_border_color = "#9C7987"
focused_border_color = "#e8d1c3"


col1 = "#DA5C28"
col2 = "#9B5E5E"
col3 = "#D87052"
col4 = "#EC9765"
col5 = "#E4AD6D"
col6 = "#9C7987"
col7 = "#e8d1c3"
col8 = "#a29288"
col9 = "#DA5C28"
col10 = "#9B5E5E"
col11 = "#D87052"
col12 = "#EC9765"
col13 = "#E4AD6D"
col14 = "#9C7987"
col15 = "#e8d1c3"



background = "#0E0908"
foreground = "#e8d1c3"
