border_width = 6
margin = [4, 4]
default_border_color = "#000001"
floating_border_color = "#91B5DB"
focused_border_color = "#cddded"


col1 = "#807E92"
col2 = "#6689B4"
col3 = "#2B89D8"
col4 = "#609CD8"
col5 = "#939EB4"
col6 = "#91B5DB"
col7 = "#cddded"
col8 = "#8f9aa5"
col9 = "#807E92"
col10 = "#6689B4"
col11 = "#2B89D8"
col12 = "#609CD8"
col13 = "#939EB4"
col14 = "#91B5DB"
col15 = "#cddded"



background = "#000001"
foreground = "#cddded"
