border_width = 6
margin = [4, 4]
default_border_color = "#011A1C"
floating_border_color = "#D2C1BE"
focused_border_color = "#e3dbda"


col1 = "#7E8188"
col2 = "#908D92"
col3 = "#A59C9E"
col4 = "#B5A9A8"
col5 = "#C8B8B6"
col6 = "#D2C1BE"
col7 = "#e3dbda"
col8 = "#9e9998"
col9 = "#7E8188"
col10 = "#908D92"
col11 = "#A59C9E"
col12 = "#B5A9A8"
col13 = "#C8B8B6"
col14 = "#D2C1BE"
col15 = "#e3dbda"



background = "#011A1C"
foreground = "#e3dbda"
