border_width = 6
margin = [4, 4]
default_border_color = "#05030C"
floating_border_color = "#C02FB3"
focused_border_color = "#a4bccf"


col1 = "#522763"
col2 = "#3D4676"
col3 = "#8B2F78"
col4 = "#3D5284"
col5 = "#4D6A98"
col6 = "#C02FB3"
col7 = "#a4bccf"
col8 = "#728390"
col9 = "#522763"
col10 = "#3D4676"
col11 = "#8B2F78"
col12 = "#3D5284"
col13 = "#4D6A98"
col14 = "#C02FB3"
col15 = "#a4bccf"



background = "#05030C"
foreground = "#a4bccf"
