border_width = 6
margin = [4, 4]
default_border_color = "#04011C"
floating_border_color = "#F39D9B"
focused_border_color = "#c8bfe5"


col1 = "#534C9B"
col2 = "#474EA1"
col3 = "#B25DAB"
col4 = "#D95B9F"
col5 = "#D28994"
col6 = "#F39D9B"
col7 = "#c8bfe5"
col8 = "#8c85a0"
col9 = "#534C9B"
col10 = "#474EA1"
col11 = "#B25DAB"
col12 = "#D95B9F"
col13 = "#D28994"
col14 = "#F39D9B"
col15 = "#c8bfe5"



background = "#04011C"
foreground = "#c8bfe5"
