border_width = 6
margin = [4, 4]
default_border_color = "#010107"
floating_border_color = "#1190AE"
focused_border_color = "#7ec6e6"


col1 = "#0A3889"
col2 = "#0F34A5"
col3 = "#0A4B90"
col4 = "#0C61A8"
col5 = "#0B6FCD"
col6 = "#1190AE"
col7 = "#7ec6e6"
col8 = "#588aa1"
col9 = "#0A3889"
col10 = "#0F34A5"
col11 = "#0A4B90"
col12 = "#0C61A8"
col13 = "#0B6FCD"
col14 = "#1190AE"
col15 = "#7ec6e6"



background = "#010107"
foreground = "#7ec6e6"
