border_width = 6
margin = [4, 4]
default_border_color = "{background}"
floating_border_color = "{color6}"
focused_border_color = "{foreground}"


col1 = "{color1}"
col2 = "{color2}"
col3 = "{color3}"
col4 = "{color4}"
col5 = "{color5}"
col6 = "{color6}"
col7 = "{color7}"
col8 = "{color8}"
col9 = "{color9}"
col10 = "{color10}"
col11 = "{color11}"
col12 = "{color12}"
col13 = "{color13}"
col14 = "{color14}"
col15 = "{color15}"



background = "{background}"
foreground = "{foreground}"
